//
//  RangersBrain.swift
//  FinalProject
//
//  Created by Zick on 12/30/17.
//  Copyright © 2017 EPITA. All rights reserved.
//

import Foundation

struct rangersBrain {
    private let rangerName = ["Gaoranger","Hurricaneger","Abaranger","Dekaranger","Magiranger","Boukenger","Gekiranger","Go-onger","Shinkenger","Goseiger","Gokaiger","Go-Busters","Kyoryuger"]
    private let rangerSubtitle = ["Power Rangers Wild Force","Power Rangers Ninja Storm","Power Rangers Dino Thunder","Power Rangers S.P.D","Power Rangers Mystic Force","Power Rangers Operation Overdrive","Power Rangers Jungle Fury","Power Rangers RPM","Power Rangers Samurai","Power Rangers Megaforce","Power Rangers Super Megaforce","No American Version","Power Rangers Dino Charge"]
    private let time = ["2001-2002","2002-2003","2003-2004","2004-2005","2005-2006","2006-2007","2007-2008","2008-2009","2009-2010","2010-2011","2011-2012","2012-2013","2013-2014"]
    private let description = [
        "Power Rangers Wild Force, often abbreviated as \"PRWF\", was the tenth incarnation of the Power Rangers series, based on Hyakujuu Sentai Gaoranger. Wild Force, like Time Force, is very faithful to its Sentai counterpart, with nearly the exact same plot. It's also the first season to have the exact same morphing sequence as its Sentai counterpart.",
        "After acquiring Power Rangers in 2002 as part of their purchase of the Fox Kids franchise, Disney decided to cancel the show at the conclusion of Power Rangers Wild Force, but were convinced to continue with the show when informed they could produce it for a fraction of the previous cost by moving production to New Zealand. As well as this, Disney chose to make the show non-union, which resulted in much of the crew (including long-time producer Jonathan Tzachor) being let go. Ninja Storm was based on the Super Sentai series Ninpū Sentai Hurricanger.",
        "A soccer player, computer expert, a musician, and a science teacher join forces to become Power Rangers and help save the Earth from mutant dinosauric beings that wish to eradicate all human life and return Earth to the age of the dinosaurs. In this season, Tommy Oliver, of Mighty Morphin Power Rangers to Power Rangers Turbo fame, returns as a paleontology professor in Reefside, California. When he is assigned three detention students, Conner, Ethan, and Kira, they end up finding the Dino Gems, paving the way for them to become the Dino Thunder Power Rangers. Conner gains the power of the Tyrannozord, as well as superspeed; Ethan gains the power of the Tricerazord, as well as the ability to make his skin super-strong; Kira gains the power of the Pterazord, as well as a sonic scream. Tommy (known often as Dr. O) himself joins the team as the Black Dino Thunder Ranger, and they are also later joined by Trent Mercer as the White Dino Thunder Ranger. ",
        "The story takes place in the year 2025, after Earth has welcomed alien beings to live peacefully with the human race. But peace is short lived, as the planet-conquering Troobian Empire turns its destructive attention to Earth. When the Earth's first line of defense, the S.P.D. A-Squad Rangers, vanishes without trace, the protection of the planet falls to their replacements: the B-Squad and their commander, Anubis Cruger. When two reformed thieves join the team as the Red and Yellow S.P.D. Rangers, tensions threaten to tear them apart. With the alien threat growing stronger every moment, the Rangers must put aside their differences and go into action as one!",
        "A short time ago, there was a dimension filled with wonderful magic. But then darkness came into power and a great battle began...An army of the Undead led by a powerful warrior - Morticon swarmed over the land setting their signs on the human realm and beyond. All seemed hopeless when a small legion of brave and true wizards came forth against insurmountable odds. They drove the evil back from the edge of the human world. And then the greatest wizard of them all - Leanbow cast a spell that sent the armies into the Underworld. He sealed darkness inside giant gates for eternity. The evil disappeared from the surface world. But with great victory comes great loss. The human world never knew of the great battle or the sacrifices that were made to save them from destruction.",
        "Many years ago, two brothers named Flurious and Moltor try to steal a legendary crown known as the Corona Aurora and are imprisoned throughout the galaxy. Sentinel Knight scatters the crown and its jewels on the planet Earth in hopes of preventing it from falling into the wrong hands. In the present day, world renowned explorer Andrew Hartford uncovers the crown, which frees Flurious and Moltor from their imprisonment. Andrew recruits four elite teenagers to become Power Rangers and stop the Corona Aurora from falling into the wrong hands. Although Hartford is originally opposed to it, his son Mack becomes the fifth team member - the Red Ranger. The Power Rangers search ancient civilizations and all over the world to uncover the first jewel which was once used by Neptune - King of Atlantis. In the process, they encounter the illustrious Miratrix, who is determined to find the jewels and free her master Kamdor.",
        "For over ten thousand years, the spirit of a pure evil known as Dai Shi has been locked away and safely guarded by the Pai Zhuq, the \"Order of the Claw,\" a secretive Kung Fu clan. But now, evil has escaped and the Pai Zhuq has selected their three top members to fight this evil. Jarrod, Lily, and Theo were picked, but Jarrod turned out to be a bad choice and Casey, a cub was to take his place. Jarrod tried taking the container holding Dai Shi. It accidentally opened; Dai Shi killed Master Mao and took over Jarrod's body. The trio was sent to find a new master and he gave them the special gift to become Power Rangers. They alone are the Earth's only hope to stop the army of evil animal spirits from overtaking the human world. Dai Shi is doing everything, and anything that he can, along with his loyal minion Camille and an army of undead, the Rinshi so he can take over the world and have animals rule. He started out with the Five Fingers of Poison, but they failed. Dai Shi controls an army of fear, and the three Power Rangers are trying to stop him.",
        "In the not-so-distant future, the mysterious and sinister Venjix Computer Network is attempting to conquer and lay ruin to the entire planet. It had succeeded and nearly conquered the entire Earth. Fortunately, mankind has retreated from the threat into environmentally-shielded domed cities to protect against the pollution and machines unleashed by Venjix. In the shining city of Corinth, an elite force of Rangers must learn to drive and operate an arsenal of radically advanced biotech vehicles in order to battle the attacking machine army bent on world domination.\nThe events of the show were intended to take place in an alternate universe, which was confirmed two years later in \"Clash of the Red Rangers\" when Scott travels to the main universe. As such, the Morphing Grid takes on a new name - the Bio Field. The only signs of previous characters are an Operation Overdrive helmet at Alphabet Soup and Jungle Karma Pizza.",
        "A new generation of Power Rangers must master the mystical and ancient \"Samurai Symbols of Power,\" which give them control over the elements of: Fire, Water, Sky, Forest, Earth and Light. Under the guidance of their all-knowing mentor and the aid of their devoted animal Zords, they battle the dark forces of the Netherworld and a mysterious warrior who is bent on destruction.\nSlogan:\n\"Rangers Together! Samurai Forever!\"",
        "Megaforce features Gosei, a supernatural being who has protected the earth for centuries with his robotic assistant, Tensou. But when the evil Warstar aliens begin their massive invasion, Gosei calls upon five teenagers with attitude to form the ultimate team...The Power Rangers Megaforce!\nWhen the teens morph into Power Rangers, they gain superhuman strength, agility, and mastery over martial arts. In addition to defending earth against the Warstar aliens, other monstrous factions emerge to challenge the Mega Rangers. Under the leadership of a malevolent alien, toxic beasts rise from their slimy underground lair to attack the Earth and a ruthless robot army launches an offensive from their deep sea compound. In order to face these new threats, the Power Rangers Megaforce unlock powerful battle modes to fight their adversaries.",
        "Power Rangers Super Megaforce focuses on the Rangers' mission to defeat a massive alien army Armada that was sent to conquer Earth. To face this threat, Gosei, a supernatural guardian who has protected Earth for centuries, gives the Rangers special morphers and keys, which allow them to morph into Super Megaforce Rangers. The Rangers also have an added special ability to morph into any team of Power Rangers from the past. These super-sized adventures can only mean one thing: the all-new Power Rangers Super Megaforce has arrived!",
        "The urban lives of the city are now run by a major power source known as Enetron (エネトロン Enetoron). An evil organization from a different dimension called Vaglass (ヴァグラス Vagurasu) aims to threaten the city by stealing the Enetron from it. Three warriors are chosen by the Energy Management Center to be a group of elite heroes, known as Tokumei Sentai Go-Busters, that will protect the city from any evil threat. Along with their partners, known as Buddy Roids (バディロイドヅ Badi Roidozu), they are tasked with stopping Vaglass from obtaining the Enetron from the city. Heroes and villains alike battle alongside 'roids' and giant villainous 'MegaZords' (メガゾード Megazōdo).",
        "Sixty-five million years ago, the legendary, transcendent Energems were given to ten dinosaurs for safekeeping by an alien named Keeper. But when Sledge, an intergalactic bounty hunter, attempted to acquire the Energems, his ship was blasted into space, leading to the extinction of the dinosaurs and the Energems being lost with them. Now, in the present day, Sledge is back and starts sniffing around Earth looking for the Energems in order to harness their power and annihilate the world, so a team of Power Rangers form to find the Energems first and fight the bounty hunter and other threats with dino-powered swords, blasters, Zords, and Megazords.\nSlogan:\n\"Power Rangers Charged!... ...Dinosaur Might, Ready To Fight! Power Rangers Dino Charge\""]
    
    let rangerLength = 13
    
    func getDetails(index : Int) ->[String]{
        return [rangerName[index],rangerSubtitle[index]]
    }
    
    func getFullDetails(index : Int) ->[String]{
        return [rangerName[index],rangerSubtitle[index],time[index],description[index]]
    }
}
